import { stateRead, stateUpdate } from "../dist/index.js";
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'state-'));
const p=path.join(dir,'state.json');
const r1=stateRead({statePath:p});
console.log('read missing',r1.exists);
if(r1.exists) throw new Error('初始应不存在');
const u1=await stateUpdate({ iteration:1, scores:{current:{total:0.8}}}, {statePath:p, historyNote:'first'});
console.log('update1',u1.state.iteration, u1.state.scores.current.total);
if(u1.state.iteration!==1) throw new Error('iteration 应 1');
if(!fs.existsSync(path.join(dir,'history','0001-iteration.json'))) throw new Error('应写 history');
const r2=stateRead({statePath:p});
if(!r2.exists || r2.state.scores.current.total!==0.8) throw new Error('读取应得到 0.8');
const u2=await stateUpdate({ scores:{current:{total:0.85}}}, {statePath:p});
console.log('update2 delta',u2.state.scores.delta);
if(u2.state.scores.delta!==0.05) throw new Error(`delta 应 0.05 得 ${u2.state.scores.delta}`);
if(u2.state.scores.history.length!==2) throw new Error('history 应 2 条');
console.log('state OK ✓');
